services:
  - type: web
    name: bhumika-portfolio
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build -p $PORT
    envVars:
      - key: NODE_VERSION
        value: "18"
    healthCheckPath: /
